config/routes.rb
Rails.application.routes.draw do
  get "/reports", to: "reports#new"
  get "/reports/show/id", to: "reports#show"
  root to: "reports#show"
  resources :projects
  
  devise_for :users, controllers: {
        sessions: 'users/sessions'}
        
      resources :reports, except: [:edit]
    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :users
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  load_and_authorize_resource
    before_action :authenticate_user!

 def index
  @report = Report.all
 end

def new
 @report = Report.new(user: current_user)
end

def create
  @report = current_user.reports.build(filtered_params)
  if @report.save
    redirect_to action: 'index'
  else
    render 'new'
  end

end
def show
  respond_to do |format|
    format.html
    format.pdf do
      render :pdf => "file_name",
             :template => "reports/show.pdf.erb",
             :layout => "pdf.html"
    end
  end
end

private
def filtered_params
 params.require(:report).permit(:statement, :user_id, project_ids: [])
end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/new.html.erb
<%= form_for @report, as: :report, url: report_path do |f|  %>

    <div class="form-group">
        <p>
        <%= form.label :project %><br>
        <%= form.select :project_ids, options_from_collection_for_select(Project.all.sort_by(&:name), :id, :name, form.object.subject_ids), {}, include_blank: true, multiple: true, class: "collect-form col-md-12"  %>
        </p>

        <p>
        <%= form.label :statement %><br>
        <%= form.text_field :statement %>
         </p>

      </div>
    </div>
    
      <div class="row">
      <div class="col-sm-6">
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
      </div>
    </div>

app/views/reports/show.pdf.erb
<h1>Reports</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |reports| %>
      <tr>
         @reports.projects.each do |s|
            <td> s.name</td>
         end 
        <td> @reports.statement</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>